# Generated by Django 5.2 on 2025-05-21 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(help_text='category name', max_length=25, null=True, unique=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru_ru',
            field=models.CharField(help_text='category name', max_length=25, null=True, unique=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_en_us',
            field=models.ForeignKey(help_text='author name', null=True, on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_ru_ru',
            field=models.ForeignKey(help_text='author name', null=True, on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='post',
            name='categories_en_us',
            field=models.ManyToManyField(help_text='categories of post', null=True, through='news.PostCategory', to='news.category', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='post',
            name='categories_ru_ru',
            field=models.ManyToManyField(help_text='categories of post', null=True, through='news.PostCategory', to='news.category', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en_us',
            field=models.TextField(help_text='post content', null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru_ru',
            field=models.TextField(help_text='post content', null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='post',
            name='rating_post_en_us',
            field=models.IntegerField(default=0, help_text='post rating', null=True, verbose_name='rating'),
        ),
        migrations.AddField(
            model_name='post',
            name='rating_post_ru_ru',
            field=models.IntegerField(default=0, help_text='post rating', null=True, verbose_name='rating'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(help_text='post title', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru_ru',
            field=models.CharField(help_text='post title', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='post',
            name='type_en_us',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], default='NW', help_text='post type', max_length=2, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='post',
            name='type_ru_ru',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], default='NW', help_text='post type', max_length=2, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='category name', max_length=25, unique=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='author name', on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(help_text='categories of post', through='news.PostCategory', to='news.category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='post content', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating_post',
            field=models.IntegerField(default=0, help_text='post rating', verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='post title', max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], default='NW', help_text='post type', max_length=2, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='PostCategory_en_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
            options={
                'verbose_name': 'post category [en-us]',
                'verbose_name_plural': 'post categorys [en-us]',
                'db_table': 'news_postcategory_en_us',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
        migrations.CreateModel(
            name='PostCategory_ru_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
            options={
                'verbose_name': 'post category [ru-ru]',
                'verbose_name_plural': 'post categorys [ru-ru]',
                'db_table': 'news_postcategory_ru_ru',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
    ]
